spring:
  profiles:
    active: dev

# 공통 설정
server:
  port: 8080
  servlet:
    context-path: /

# 한국투자증권 OpenAPI 공통 설정
kis:
  api:
    base-url: https://openapi.koreainvestment.com:9443
    app-key: ${KIS_APP_KEY}
    app-secret: ${KIS_APP_SECRET}

# 로깅 설정
logging:
  level:
    trade.project.common.client: DEBUG
    trade.project.api.client: DEBUG
    org.springframework.web.reactive.function.client: DEBUG

