spring:
  application:
    name: project

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:13306/trade_dev?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${secret.username}
    password: ${secret.password}

mybatis:
  mapper-locations: classpath:xml/*.xml
  configuration:
    map-underscore-to-camel-case: true

# 한국투자증권 OpenAPI 설정 (개발용)
kis:
  api:
    base-url: https://openapi.koreainvestment.com:9443
    app-key: ${KIS_APP_KEY}
    app-secret: ${KIS_APP_SECRET}

# 로깅 설정 (개발용 - 상세 로그)
logging:
  level:
    trade.project: DEBUG
    trade.project.common.client: DEBUG
    trade.project.api.client: DEBUG
    org.springframework.web.reactive.function.client: DEBUG
    root: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n" 