spring:
  application:
    name: dev

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:finance}?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${DB_USERNAME:${USER_NAME}}
    password: ${DB_PASSWORD:${PASSWORD}}

  data:
    mongodb:
      host: ${DB_HOST:localhost}
      port: ${MONGO_PORT:27017}
      database: ${DB_NAME:finance}

# 한국투자증권 OpenAPI 설정 (개발용)
kis:
  api:
    base-url: https://openapi.koreainvestment.com:9443
    app-key: ${KIS_APP_KEY}
    app-secret: ${KIS_APP_SECRET}

naver:
  api:
    client-id: ${NAVER_CLIENT_ID}
    client-secret: ${NAVER_CLIENT_SECRET}

# 로깅 설정 (개발용 - 상세 로그)
logging:
  level:
    trade.project: DEBUG
    trade.project.common.client: DEBUG
    trade.project.api.client: DEBUG
    org.springframework.web.reactive.function.client: DEBUG
    root: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

newsapi:
  api:
    key: ${NEWSAPI_API_KEY}